name: off_the_hook
description: A YouTube app designed to keep you off their hook. 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  async: ^2.11.0
  chewie: ^1.7.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  localstorage: ^4.0.1+4
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/icons/
  fonts:
    - family: Assistant
      fonts:
        - asset: lib/assets/fonts/Assistant-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Assistant-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Assistant-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Assistant-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Assistant-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Assistant-ExtraBold.ttf
          weight: 800
        