int resolutionIndex = 2; // Max Resolution
int videosToFetch = 8;

class Channel {
  final String name;
  final String id;
  final String pfp;
  final String description;

  final int subCount;

  final bool isFamilyFriendly;
  final bool isAutoGenerated; // Need to ignore channels like this.
  final bool isSubscribed;

  final List<String> latestVideosIDs;

  const Channel(
      {required this.name,
      required this.id,
      required this.pfp,
      required this.description,
      required this.isFamilyFriendly,
      required this.isAutoGenerated,
      required this.isSubscribed,
      this.subCount = 0,
      this.latestVideosIDs = const []});

  factory Channel.fromJson(Map<String, dynamic> json) {
    List<String> latestVideosIDs = [];
    List<dynamic> latestVideos = json['latestVideos'];
    for (int i = 0;
        i <
            (latestVideos.length < videosToFetch
                ? latestVideos.length
                : videosToFetch);
        i++) {
          
      latestVideosIDs.add(latestVideos[i]['videoId']);
    }
    return Channel(
        name: json['author'],
        id: json['authorId'],
        pfp: json['authorThumbnails'][resolutionIndex]['url'],
        description: json['description'],
        isFamilyFriendly: json['isFamilyFriendly'],
        isAutoGenerated: json['autoGenerated'],
        isSubscribed: json['isSubscribed'],
        subCount: json['subCount'],
        latestVideosIDs: latestVideosIDs);
  }
}

