import 'package:LibreMedia/classes/subscriptions.dart';
import 'package:flutter/material.dart';
import 'package:LibreMedia/widgets/video-card.dart';

//TODO: add pages to see channel history.

class ChannelProfile extends StatefulWidget {
  final String name;
  final String id;
  final String pfp;
  final String description;

  final int subCount;

  final bool isFamilyFriendly;
  final bool isAutoGenerated; // Need to ignore channels like this.
  final bool isSubscribed;

  final List<String> latestVideosIDs;

  const ChannelProfile(
      {super.key,
      required this.name,
      required this.id,
      required this.pfp,
      required this.description,
      required this.isFamilyFriendly,
      required this.isAutoGenerated,
      required this.isSubscribed,
      this.subCount = 0,
      this.latestVideosIDs = const []});

  @override
  State<ChannelProfile> createState() => _ChannelProfileState();
}

class _ChannelProfileState extends State<ChannelProfile> {
  late bool isSubbed = widget.isSubscribed;

  _toggleSubscribe() async {
    if (isSubbed) {
      await Subscriptions().removeSubscription(widget.id);
      setState(() {
        isSubbed = false;
      });
      return;
    }
    await Subscriptions().addToSubscriptions(widget.id);
    setState(() {
      isSubbed = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        ClipRRect(
            borderRadius: BorderRadius.circular(600),
            child: Image.network(widget.pfp)),
        const SizedBox(height: 15),
        Expanded(
          child: ListView.builder(
            physics: const BouncingScrollPhysics(),
            itemCount: widget.latestVideosIDs.length,
            itemBuilder: (context, index) =>
                FutureVideoCard(videoId: widget.latestVideosIDs[index]),
          ),
        ),
        ElevatedButton(
            onPressed: _toggleSubscribe,
            child: isSubbed
                ? const Text("Subscribed")
                : const Text("Subscribe"))
      ],
    );
  }
}
